export const themes = {
  light_theme: {
      '--bannerTitle': '#000000',
      '--mainHeader': '#FEFEFE',
      '--bannerSubTitile': '#000000',
      '--createMeetingBtn': '#E6790C',
      '--createMeetingBtnColor': '#ffffff',
      '--copyLinkInput': '#ffffff',
      '--meetingJoinBtn': '#E6790C',
      '--meetingJoinBtnColor': '#ffffff',
      '--mainHeading': '#000000',
      '--mainSubHeading': '#000000',
      '--beforeBgColor': '#fcfcfc',
      '--cardBg': '#BFD6D2',
      '--cardHeading': '#000000',
      '--cardSubHeading': '#000000',
      '--lINKWithPrideBox': '#BFD6D2',
      '--lINKWithPrideBoxBefore': 'linear-gradient(228deg, rgba(125, 151, 146, 0.24) 25.68%, rgba(125, 151, 146, 0) 86.96%);',
      '--lINKWithPrideBoxHeading': '#000000',
      '--lINKWithPrideBoxSubHeading': '#000000',
      '--deviceSectionBoxBg': '#BFD6D2',
      '--deviceSectionBoxBefore': 'linear-gradient(184deg, #E0E6E5 3.55%, rgba(224, 230, 229, 0.00) 43.89%)',
      '--meetOnAnyDeviceSectionBoxBg': 'rgba(231, 236, 235, 0.28)',
      '--meetOnAnyDeviceSectionBoxHeading': '#000000',
      '--meetOnAnyDeviceSectionBoxSubHeading': '#000000',
      '--lINKEducationBoxBg': '#BFD6D2',
      '--lINKEducationBoxBgBefore': 'linear-gradient(86deg, rgba(125, 151, 146, 0.24) 25.68%, rgba(125, 151, 146, 0.00) 86.96%)',
      '--lINKEducationBoxHeading': '#000000',
      '--lINKEducationBoxSubheading': '#000000',
      '--featureSubSectionBgBefore': 'linear-gradient(346deg, #EDF1F0 13.84%, rgba(234, 238, 237, 0.15) 81.06%)',
      '--featureSubSectionSubHeading': '#000000',
      '--featureSubSectionBorderBg': '#000000',
      '--knowMoreBtn': '#0C9E9B',
      '--planSubHeading': '#0C9E9B',
      '--meetingSizeHeading': '#000000',
      '--planListNewHeading': '#000000',
      '--planListNewBorder': '#0C9E9B',
      '--planListBeforeColor': '#0C9E9B',
      '--planListColor': '#000000',
      '--planListSubHeadingColor': '#000000',
      '--testimonialsSectionSubHeading': '#000000',
      '--testimonialsSectionHeading': '#000000',
      '--mainFooterBg': '#B3CFEB',
      '--mainFooterColor': '#000000',
      '--mainFooterHeadingColor': '#000000',
      '--mainFooterBorder': '#000000',
      '--mainFooterListColor': '#000000',
      '--mainFooterSubHeading': '#000000',
      '--mainFooterLogoHeading': '#000000',
      '--mainFooterLogoBg': '#B3CFEB',
      '--subscriptionSectionBroder': '#121213',
      '--socialIconsColor': '#121213',



      /**********************************************************************/
      '--bgPrimaryContainer': '#b9dbcd',
    '--bgSecondaryContainer': '#d2e8de',
    '--bgToggleButton': '#7ab8b7',
    '--bgToggleSecondaryButton': '#e2e2e2',
    '--label': '#000000',
    '--bgChatBox': '#fffbfb',
    '--bgPlaceholderLabel': '#eaf2f0',
    '--bgChatInput': '#7ab8b7',
    '--bgSendIcon': '#a0d3cb',
    '--sendBtnIcon': '#e5ecea',
    '--bgMenuIcons': '#c9c9c9',
    '--crossMenuIcon': '#8d9bad',
    '--menuIcons': '#919395',
    '--menuEndMeeting': '#f56d6d',
    '--bgChatGPTIcon': '#74aa9c',
    '--chatGPTIcon': '#ffffff',
    '--bgChatGpt': '#e3efe8',
    '--bgChatGptMessageBox': '#ffffff',
    '--bgChatMessageBox': '#d6e4e0',
    '--bgVcChatEmoji': '#fbf9f8',
    '--vcChatEmojiIcon': '#91C7BA',
    '--mainPageBgLeft': '#339694',
    '--mainPageBgRight': '#ffffff',
    '--mainPageBannerText': '#000000',
    '--joinButton': '#52CBC9',
    '--vcExpandIcon': '#000000',
    '--bgMeetingMenu': '#ffffff',
    '--bgVcChatGptProfileImage': '#cfddd7',
    '--iconsColorDarkLight': '#b9dbcd',
    '--bgMainPage':'#ffffff',
    '--dialogCloseBtn': '#000000',
    '--waitingRoomCard': '#ffffff',
    '--waitingRoomText': '#000000',
    '--projectionSubmitbuttonBg':'#339694',
    '--projectionSubmitbuttonColor':'#ffffff',
    '--projectionCancelbuttonBg':'#ffffff',
    '--projectionCancelbuttonColor':'#339694',
    '--bodyBg':'#ffffff',
    '--iconTheme':'#000',
    '--bgHeader':'#FEFEFE',
    '--liveclock':'#000',
    '--planListBg':'rgba(198, 233, 250, 0.84)',
    '--aiezeLogoColor':'#000'

  },
  dark_theme: {
      '--bannerTitle': '#ffffff',
      '--mainHeader': '#222226',
      '--bannerSubTitile': '#ffffff',
      '--createMeetingBtn': '#0C9E9B',
      '--createMeetingBtnColor': '#ffffff',
      '--copyLinkInput': '#ffffff',
      '--meetingJoinBtn': '#0c9e9b',
      '--meetingJoinBtnColor': '#ffffff',
      '--mainHeading': '#ffffff',
      '--mainSubHeading': '#ffffff',
      '--beforeBgColor': '#262628',
      '--cardBg': '#1A1A1E',
      '--cardHeading': '#ffffff',
      '--cardSubHeading': '#ffffff',
      '--lINKWithPrideBox': '#1D1D21',
      '--lINKWithPrideBoxBefore': 'linear-gradient(228deg, rgba(125, 151, 146, 0.24) 25.68%, rgba(125, 151, 146, 0.00) 86.96%)',
      '--lINKWithPrideBoxHeading': '#ffffff',
      '--lINKWithPrideBoxSubHeading': '#ffffff',
      '--deviceSectionBoxBg': '#1A1A1E',
      '--deviceSectionBoxBefore': 'linear-gradient(228deg, rgba(125, 151, 146, 0.24) 25.68%, rgba(125, 151, 146, 0.00) 86.96%)',
      '--meetOnAnyDeviceSectionBoxBg': '#161619',
      '--meetOnAnyDeviceSectionBoxHeading': '#ffffff',
      '--meetOnAnyDeviceSectionBoxSubHeading': '#ffffff',
      '--lINKEducationBoxBg': '#1D1D21',
      '--lINKEducationBoxBgBefore': 'linear-gradient(228deg, rgba(125, 151, 146, 0.24) 25.68%, rgba(125, 151, 146, 0.00) 86.96%)',
      '--lINKEducationBoxHeading': '#ffffff',
      '--lINKEducationBoxSubheading': '#ffffff',
      '--featureSubSectionBgBefore': 'linear-gradient(343deg, #2A3031 13.74%, rgba(42, 48, 49, 0.00) 87.51%)',
      '--featureSubSectionSubHeading': '#ffffff',
      '--featureSubSectionBorderBg': '#ffffff',
      '--knowMoreBtn': '#ffffff',
      '--planSubHeading': '#0C9E9B',
      '--meetingSizeHeading': '#ffffff',
      '--planListNewHeading': '#ffffff',
      '--planListNewBorder': '#ffffff',
      '--planListBeforeColor': '#ffffff',
      '--planListColor': '#ffffff',
      '--planListSubHeadingColor': '#ffffff',
      '--testimonialsSectionSubHeading': '#ffffff',
      '--testimonialsSectionHeading': '#ffffff',
      '--mainFooterBg': '#121213',
      '--mainFooterColor': '#ffffff',
      '--mainFooterHeadingColor': '#ffffff',
      '--mainFooterBorder': '#ffffff',
      '--mainFooterListColor': '#ffffff',
      '--mainFooterSubHeading': '#ffffff',
      '--mainFooterLogoHeading': '#ffffff',
      '--mainFooterLogoBg': '#121213',
      '--subscriptionSectionBroder': '#ffffff',
      '--socialIconsColor': '#ffffff',


      /**********************************************************************/
      '--bgPrimaryContainer': '#232323',
    '--bgSecondaryContainer': '#181a1b',
    '--bgToggleButton': '#0e7977',
    '--bgToggleSecondaryButton': '#2b2b2b',
    '--label': '#ffffff',
    '--bgChatBox': '#181A1B',
    '--bgPlaceholderLabel': '#304243',
    '--bgChatInput': '#304243',
    '--bgSendIcon': '#0e7977',
    '--sendBtnIcon': '#8bbfc3',
    '--bgMenuIcons': '#575757',
    '--crossMenuIcon': '#242b34',
    '--menuIcons': '#96ef88',
    '--menuEndMeeting': '#d75555',
    '--bgChatGPTIcon': '#74aa9c',
    '--bgChatGptMessageBox': '#2b2b2b',
    '--chatGPTIcon': '#ffffff',
    '--bgChatGpt': '#18211c',
    '--bgChatMessageBox': '#2b2b2b',
    '--bgVcChatEmoji': '#1b2825',
    '--vcChatEmojiIcon': '#6B7B87',
    '--mainPageBgLeft': '#0B6462',
    '--mainPageBgRight': '#232323',
    '--mainPageBannerText': '#ffffff',
    '--joinButton': '#52CBC9',
    '--vcExpandIcon': '#ffffff',
    '--bgMeetingMenu': '#181a1b',
    '--iconsColorDarkLight': '#fff',
    '--bgMainPage':'#000000',
    '--dialogCloseBtn': '#ffffff',
    '--waitingRoomCard': '#000000',
    '--waitingRoomText': '#ffffff',
    '--projectionSubmitbuttonBg':'#0B6462',
    '--projectionSubmitbuttonColor':'#ffffff',
    '--projectionCancelbuttonBg':'#ffffff',
    '--projectionCancelbuttonColor':'#0B6462',
    '--bodyBg':'#101013',
    '--iconTheme':'#fff',
    '--bgHeader':'#222226',
    '--liveclock':'#fff',
    '--planListBg':'#404344',
    '--aiezeLogoColor':'#fff'
  },
};
